version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - authentication_microservice-network
  authentication_microservice:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_started
    networks:
      - authentication_microservice-network
networks:
  authentication_microservice-network:
    driver: bridge
