
spring:
  datasource:
    url: jdbc:postgresql://db:5432/testdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param
    include-exception: false

application:
  security:
    jwt:
      secret-key: 676BCA12F6C06F2094DB9BB9CD45C209566900D782AC3C3C902D6C9697DD7DC6
      value-of-day: 86400000